# Generated by Django 5.0.6 on 2024-05-29 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_harga", models.IntegerField()),
                ("alamat_asal", models.CharField(max_length=200)),
                ("alamat_tujuan", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                ("alamat", models.CharField(default=None, max_length=200)),
                (
                    "no_telp",
                    models.CharField(
                        blank=True, default=None, max_length=14, null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfoPenjemputan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_kontak", models.CharField(max_length=200)),
                ("no_kontak", models.CharField(max_length=200)),
                ("kode_pos", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("detail_lokasi", models.CharField(max_length=200)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sampah.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sampah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("KRS", "KERTAS"),
                            ("PLC", "PLASTIC"),
                            ("MTL", "METAL"),
                        ],
                        max_length=200,
                    ),
                ),
                ("jumlah", models.IntegerField()),
                ("deskripsi", models.CharField(max_length=200)),
                (
                    "tag",
                    models.CharField(
                        choices=[("DRY", "KERING"), ("WET", "BASAH")], max_length=6
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("AVL", "AVAILABLE"), ("SLD", "SOLD")], max_length=8
                    ),
                ),
                (
                    "foto_sampah",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to=""
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sampah.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sampah.customer",
                    ),
                ),
                (
                    "sampah",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sampah.sampah"
                    ),
                ),
                (
                    "transaction_invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sampah.invoice"
                    ),
                ),
            ],
        ),
    ]
