# Generated by Django 5.0.2 on 2024-05-25 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sampah", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_harga", models.IntegerField()),
                ("alamat_asal", models.CharField(max_length=200)),
                ("alamat_tujuan", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="sampah",
            name="status",
            field=models.CharField(
                choices=[("AVL", "AVAILABLE"), ("SLD", "SOLD")], max_length=8
            ),
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sampah.customer",
                    ),
                ),
                (
                    "sampah",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sampah.sampah"
                    ),
                ),
                (
                    "transaction_invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sampah.invoice"
                    ),
                ),
            ],
        ),
    ]
