# Generated by Django 5.0.6 on 2024-05-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sampah", "0004_infopenjemputan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sampah",
            old_name="user",
            new_name="customer",
        ),
        migrations.AlterField(
            model_name="sampah",
            name="jenis",
            field=models.CharField(
                choices=[("KRS", "KERTAS"), ("PLC", "PLASTIC"), ("MTL", "METAL")],
                max_length=200,
            ),
        ),
    ]
