# Generated by Django 5.0.6 on 2024-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sampah", "0005_rename_user_sampah_customer_alter_sampah_jenis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sampah",
            name="tag",
            field=models.CharField(
                choices=[("DRY", "KERING"), ("WET", "BASAH")], max_length=6
            ),
        ),
    ]
