# Generated by Django 5.0.6 on 2024-05-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sampah", "0006_alter_sampah_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="no_telp",
            field=models.IntegerField(default=None),
        ),
    ]
